netgen_remote_media_upload:
    path: /ngremotemedia/upload/{contentId}
    defaults: { _controller: netgen_remote_media.controller.ui:uploadFileAction }

netgen_remote_media_upload_simple:
    path: /ngremotemedia/simple_upload
    defaults: { _controller: netgen_remote_media.controller.ui:uploadFileSimpleAction }

netgen_remote_media_fetch:
    path: /ngremotemedia/fetch/{contentId}/{fieldId}/{contentVersionId}
    defaults: { _controller: netgen_remote_media.controller.ui:fetchAction }

netgen_remote_media_save:
    path: /ngremotemedia/save/{contentId}/{fieldId}/{contentVersionId}
    defaults: { _controller: netgen_remote_media.controller.ui:updateCoordinatesAction }

netgen_remote_media_browse:
    path: /ngremotemedia/browse
    defaults: { _controller: netgen_remote_media.controller.ui:browseRemoteMediaAction }

netgen_remote_media_add_tag:
    path: /ngremotemedia/tags/{contentId}/{fieldId}/{contentVersionId}
    defaults: { _controller: netgen_remote_media.controller.ui:addTagsAction }
    methods: [POST]

netgen_remote_media_remove_tag:
    path: /ngremotemedia/tags_delete/{contentId}/{fieldId}/{contentVersionId}
    defaults: { _controller: netgen_remote_media.controller.ui:removeTagsAction }
    methods: [POST]

netgen_remote_media_fetch_remote:
    path: /ngremotemedia/simple_fetch
    defaults: { _controller: netgen_remote_media.controller.ui:fetchRemoteAction }

netgen_remote_media_generate_variation:
    path: /ngremotemedia/generate
    defaults: { _controller: netgen_remote_media.controller.ui:generateVariationAction }
