netgen_remote_media_upload:
    path: /ezexceed/remotemedia/upload
    defaults: { _controller: NetgenRemoteMediaBundle:UI:uploadFile }

netgen_remote_media_fetch:
    path: /ezexceed/ngremotemedia/fetch/{attributeId}/{contentVersionId}
    defaults: { _controller: NetgenRemoteMediaBundle:UI:fetch }

netgen_remote_media_save:
    path: /ezexceed/ngremotemedia/save/{objectId}/{attributeId}/{contentVersionId}
    defaults: { _controller: NetgenRemoteMediaBundle:UI:saveAttribute }

netgen_remote_media_browse:
    path: /ezexceed/ngremotemedia/browse/{attributeId}/{contentVersionId}
    defaults: { _controller: NetgenRemoteMediaBundle:UI:browseRemoteMedia }

netgen_remote_media_add_tag:
    path: /ezexceed/ngremotemedia/tags/{attributeId}/{contentVersionId}
    defaults: { _controller: NetgenRemoteMediaBundle:UI:addTags }
    methods: [POST]

netgen_remote_media_remove_tag:
    path: /ezexceed/ngremotemedia/tags/{attributeId}/{contentVersionId}
    defaults: { _controller: NetgenRemoteMediaBundle:UI:removeTags }
    methods: [DELETE]

netgen_remote_media_fetch_remote:
    path: /ezexceed/ngremotemedia/fetch_remote/{id}
    defaults: { _controller: NetgenRemoteMediaBundle:UI:fetchRemote }
    requirements:
        id: .+
