parameters:
    netgen_remote_media.provider: "netgen_remote_media.remote_media.cloudinary"

services:
    netgen_remote_media.controller.ui:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\UIController
        arguments:
            - "@netgen_remote_media.remote_media.provider"
            - "@netgen_remote_media.helper"
            - "@templating"
            - "@ezpublish.api.repository"
            - "@ezpublish.config.resolver"
            - "@security.authorization_checker"
        calls:
            - [setAnonymousUserId, ["$anonymous_user_id$"]]
            - [setBrowseLimit, ["$ezexceed.browse_limit;netgen_remote_media$"]]

    netgen_remote_media.remote_media.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\CloudinaryProvider
        arguments:
            - "$cloudinary;netgen_remote_media$"

    netgen_remote_media.helper:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Helper
        arguments:
            - "@netgen_remote_media.remote_media.provider"
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.content_type"
