parameters:
    netgen_remote_media.default.cloudinary.folder_name: ''
    netgen_remote_media.default.cloudinary.unique_id: false
    netgen_remote_media.default.cloudinary.use_upscaling: true
    netgen_remote_media.default.use_content_version_as_part_of_filename: true

services:
    netgen_remote_media.handler_registry:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Transformation\Registry

    netgen_remote_media.controller.ui:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\UIController
        arguments:
            - "@netgen_remote_media.provider"
            - "@netgen_remote_media.helper"
            - "@templating"
            - "@ezpublish.api.repository"
            - "@ezpublish.config.resolver"
            - "@security.authorization_checker"
        calls:
            - [setAnonymousUserId, ["$anonymous_user_id$"]]
            - [setBrowseLimit, ["%netgen_remote_media.browse_limit%"]]
            - [setEzoeVariationList, ["%netgen_remote_media.ezoe.variation_list%"]]
            - [setEzoeClassList, ["%netgen_remote_media.ezoe.class_list%"]]

    netgen_remote_media.variation.resolver:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\VariationResolver
        calls:
            - [setVariations, ["$image_variations;netgen_remote_media$"]]


    netgen_remote_media.provider.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\CloudinaryProvider
        arguments:
            - "@netgen_remote_media.handler_registry"
            - "@?logger"
            - "%netgen_remote_media.parameters.cloudinary.account_name%"
            - "%netgen_remote_media.parameters.cloudinary.account_key%"
            - "%netgen_remote_media.parameters.cloudinary.account_secret%"
        calls:
            - [setFolderName, ["$cloudinary.folder_name;netgen_remote_media$"]]
            - [setUniqueFilename, ["$cloudinary.unique_id;netgen_remote_media$"]]

    netgen_remote_media.helper:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Helper
        arguments:
            - "@netgen_remote_media.provider"
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.content_type"
        calls:
            - [setContentVersionInFileName, ["$use_content_version_as_part_of_filename;netgen_remote_media$"]]
