parameters:
    netgen_remote_media.provider: "netgen_remote_media.remote_media.cloudinary"

services:
    ezpublish.fieldType.ngremotemedia:
        class: Netgen\Bundle\RemoteMediaBundle\Core\FieldType\RemoteMedia\Type
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ngremotemedia}

    ezpublish.fieldType.ngremotemedia.converter:
        class: Netgen\Bundle\RemoteMediaBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\RemoteMediaConverter
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ngremotemedia}

    ezpublish.fieldType.ngremotemedia.externalStorage:
        class: Netgen\Bundle\RemoteMediaBundle\Core\FieldType\RemoteMedia\RemoteMediaStorage\CloudinaryStorage
        arguments:
            - "@ezpublish.api.service.content"
            - "@netgen_remote_media.remote_media.provider"
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ngremotemedia}

    netgen_remote_media.remote_media.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\CloudinaryProvider
        arguments:
            - "$cloudinary;netgen_remote_media$"
