parameters:
    netgen_remote_media.default.cloudinary.folder_name: ''

services:
    netgen_remote_media.handler_registry:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Transformation\Registry

    netgen_remote_media.variation.resolver:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\VariationResolver
        calls:
            - [setVariations, ["$image_variations;netgen_remote_media$"]]


    netgen_remote_media.provider.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\CloudinaryProvider
        arguments:
            - "@netgen_remote_media.handler_registry"
            - "@netgen_remote_media.variation.resolver"
            - "@?logger"
        calls:
            - [initCloudinary, ['%netgen_remote_media.parameters.cloudinary.account_name%', '%netgen_remote_media.parameters.cloudinary.account_key%', "%netgen_remote_media.parameters.cloudinary.account_secret%"]]
            - [setFolderName, ["$cloudinary.folder_name;netgen_remote_media$"]]

    netgen_remote_media.helper:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Helper
        arguments:
            - "@netgen_remote_media.provider"
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.content_type"
