services:
    netgen_remote_media.handler.cloudinary.fill:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\TransformationHandler\Fill
        lazy: true
        tags:
            - { name: netgen_remote_media.transformation_handler, alias: fill, provider: cloudinary }
