services:
    netgen_remote_media.command.api_usage:
        class: Netgen\Bundle\RemoteMediaBundle\Command\ShowApiUsageCommand
        arguments:
            - "@netgen_remote_media.provider"
        tags:
            - { name: console.command }
