services:
    netgen_remote_media.controllers.ezadminui.facets.load:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\Facets\Load
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controllers.ezadminui.folder.load:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\Folder\Load
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controllers.ezadminui.folder.create:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\Folder\Create
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controllers.ezadminui.browse:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\BrowseController
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.helper'

    netgen_remote_media.controllers.ezadminui.editor.insert:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\Editor\InsertController
        arguments:
            - '@netgen_remote_media.admin.field_update.helper'
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.helper'
