services:
    netgen_remote_media.controllers.ezadminui.folders.list:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\Folders\ListController
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controllers.ezadminui.browse:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\BrowseController
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.helper'

    netgen_remote_media.controllers.ezadminui.fetch:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\FetchController
        arguments:
            - '@netgen.ezplatform_site.load_service'

    netgen_remote_media.controllers.ezadminui.load:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\LoadController
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controllers.ezadminui.change:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\ChangeController
        arguments:
            - '@netgen_remote_media.provider'
            - '@ezpublish.api.repository'

    netgen_remote_media.controllers.ezadminui.save:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\SaveController
        arguments:
            - '@ezpublish.api.repository'
