netgen_remote_media_ezadmin_facets_load:
    path: /facets/load
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.facets.load

netgen_remote_media_ezadmin_folder_load:
  path: /folder/load
  defaults:
    _controller: netgen_remote_media.controllers.ezadminui.folder.load

netgen_remote_media_ezadmin_folder_create:
  path: /folder/create
  defaults:
    _controller: netgen_remote_media.controllers.ezadminui.folder.create

netgen_remote_media_ezadmin_browse:
    path: /browse
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.browse

netgen_remote_media_ezadmin_editor_fetch:
    path: /editor/fetch
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.editor.fetch

netgen_remote_media_ezadmin_editor_insert:
    path: /editor/insert
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.editor.insert
