netgen_remote_media_ezadmin_facets_load:
    path: /facets/load
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.facets.load

netgen_remote_media_ezadmin_folder_load:
  path: /folder/load
  defaults:
    _controller: netgen_remote_media.controllers.ezadminui.folder.load

netgen_remote_media_ezadmin_browse:
    path: /browse
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.browse

netgen_remote_media_ezadmin_editorinsert:
    path: /editorinsert
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.editorinsert
