netgen_remote_media_ezadmin_facets:
    path: /facets
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.facets.list

netgen_remote_media_ezadmin_sub_folders:
  path: /subfolders
  defaults:
    _controller: netgen_remote_media.controllers.ezadminui.sub_folders.list

netgen_remote_media_ezadmin_browse:
    path: /browse
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.browse

netgen_remote_media_ezadmin_editorinsert:
    path: /editorinsert
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.editorinsert
