folders:
    path: /folders
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.folders.list

browse:
    path: /browse
    defaults:
        _controller: netgen_remote_media.controllers.ezadminui.browse
