services:
    netgen_remote_media.content_browser.backend.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\ContentBrowser\Backend\CloudinaryBackend
        arguments:
            - "@netgen_remote_media.provider.cloudinary"
        tags:
            - { name: netgen_content_browser.backend, item_type: cloudinary }
