name: Coding standards

on:
  push:
    branches:
      - 'master'
  pull_request: ~

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: OskarStark/php-cs-fixer-ga@2.19.0
        with:
          args: --diff --dry-run
